name: CI
on:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: print test message
      run: echo "Hello Test"
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: print deploy message
      run: echo print "Hello Deploy"
