name: CI

env:
  APPLICATION_NAME: "Flask test"
  PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"
  
on:
  push:
    branches:
    - master
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: print test message
      run: echo "Hello Test"
    - name: execute few commands
      run: |
        echo "first message"
        echo "second message"
        echo "application name: ${{ env.APPLICATION_NAME }}"
    - name: list current folder
      run: ls -la
      
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: print deploy message
      run: echo print "Hello Deploy"
    - name: deploytment package
      run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
